### ISSUE TITLE
CI: Always run ` run_tutorials` when the .ipynb files change

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#3945]
Changing tutorials but not variable subsitutions in CI may cause late failues in the weekly schedule.
This would prevent at least those cases, where it was triggered by a changed ipynb file.

Implementation:
Using `only: changes` or `rules: changes`
care has to be taken that the `run_totrials` runs whenever `deploy_tutorials` does, as well

**Comment by jngrad** [comment]
I've experimented with the [`only:`](https://docs.gitlab.com/ee/ci/yaml/#onlyexcept-advanced) keyword in GitLab projects recently, and from what I've learned, it should probably look like this:
```yaml
run_tutorials:
  only:
    changes:
      - doc/tutorials
      - .gitlab-ci.yml
```
instead of the current form:
```yaml
run_tutorials:
  only:
    variables:
      - $CI_COMMIT_REF_NAME == "python" && $CI_DEPLOY_TUTORIALS
```
This way the tutorials are built in PRs that change them, or change the docker image. This won't build tutorials on side-effects though, e.g. changes in the top-level `CMakeLists.txt` or `cmake/` that may influence how the tutorials are built.

The deploy job would be written the same way, but would only deploy on merges:
```yaml
deploy_tutorials:
  only:
    changes:
      - doc/tutorials
      - .gitlab-ci.yml
    variables:
      - $CI_COMMIT_REF_NAME == "python"
```

If this strategy doesn't work out, we could keep it simple and move the job from the weekly builds to the nightly builds.
